# payment-postgres/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-postgres-config
  namespace: payment-postgres
  labels:
    app.kubernetes.io/name: payment-postgres
    app.kubernetes.io/component: config
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_HOST_payment_METHOD: "scram-sha-256"
